### PR TITLE
fix warnings about deprecation of ScopedPointer

### PR DESCRIPTION
**Pull request by jpcima**
It's my unique_ptr conversion branch. Not all there is in the deprecation department, but a good deal of it.

There are also some reordering of initializers (-Wreorder)

For at aleast one case, I have converted it to an ordinary pointer.
It's objects used with `setContentOwned`, and because their lifetime will be managed by their owner, I don't think they must be held by automatic pointers.

A thing I noticed is a segfault when closing CabbageLite, which I don't know if it's my fault or not, I was going to debug it.

### CODE REVIEW

**Comment by rorywalsh** [comment]
Brilliant 👏

**Comment by rorywalsh** [comment]
I'm getting some crashes on shutdown on Windows, but I'm happy to look into these myself 😉

**Comment by rorywalsh** [comment]
I pushed through a fix for the crash I was getting on shutdown. Everything looks pretty good, but I'll give it more testing now.

**Comment by rorywalsh** [comment]
Hi @jpcima . It looks like there are still some issues with this. The GUI editor keep crashing now due to some strange string problems. I think I may revert back to an earlier commit? It's probably best to create an entirely new branch for this commit considering the scope of the changes. What do you think?

**Comment by jpcima** [comment]
Revert it as you please, there is certainly a problem of ownerships which I did not understand too well. I didn't manage to get to the end of this last time I debugged, will recheck when I have time.
I remember it related to continuing accessing a component, after being destroyed.

**Comment by rorywalsh** [comment]
I think it might be best to work through from the state you were on. I'll give it a whirl and see if I can sort out the few niggling things. I have to drop ScopedPointer anyway, so a bit of pain now will be worth it in the end. Cheers.

**Pull request merged**
