### PR TITLE
Add .csd filename to message logged when .csd is not found

### PR DESCRIPTION
**Pull request by andy-fillebrown**

### CODE REVIEW

**Review by rorywalsh — APPROVED** [review]
Great

**Comment by rorywalsh** [comment]
There was n issue here in that `filename` was not valid, I've fixed and updated the dev branch. 👍

**Comment by andy-fillebrown** [comment]
I don't think you meant `csdFile.loadFileAsString()`. That will attempt to log the entire contents of a non-existent .csd. Maybe `csdFile.getFileName()` or `csdFile.getFullPathName()`?

**Comment by rorywalsh** [comment]
Of course. Auto-complete.. fixed now.

**Pull request merged**
