### PR TITLE
Parameter suffixes & cleaner ownership semantics

### PR DESCRIPTION
**Pull request by awelex**
More parameter work in this PR:
- `addCabbageParameter` now takes a `unique_ptr` instead of a naked pointer to clarify ownership
- There is a new `suffix` identifier for widgets, defaulting to `""`. Hosts will display the suffix next to the parameter value. This can be used to indicate units such as dB, Hz, etc.

### CODE REVIEW

**Comment by rorywalsh** [comment]
This is a really nice addition. Thanks. I'll merge once it passes the tests, although Azure is choking on Windows builds at the moment..

**Comment by tgrey1** [comment]
> There is a new suffix identifier for widgets, defaulting to "". Hosts will display the suffix next to the parameter value. This can be used to indicate units such as dB, Hz, etc.

Just curious... how does this differ from, or does it replace popuppostfix()?

**Comment by awelex** [comment]
> Just curious... how does this differ from, or does it replace popuppostfix()?
Interesting, I wasn't aware of `popuppostfix`. Just checked it out. Here are the differences:

- `suffix` communicates the suffix to the host, so it will show up on automation lanes, generic sliders that the host supplies and wherever else the host displays parameter values. `popuppostfix` only applies to the popup bubbles a Cabbage plug-in can display.
- `popuppostfix` seems to be limited to sliders, whereas `suffix` applies to all automatable widgets.

I was already going to amend `suffix` to show the suffix not just in the host but also wherever parameter values are shown in the plug-in GUI. But given that there is some overlap in functionality I wonder what the best way to proceed is. It makes sense for me to have one single mechanism that a) works for all widgets and b) shows the suffix both in the GUI and in the host. Because of that I think it makes sense for `suffix` to replace `popuppostfix`. (`popuppostfix` could of course still be kept around for backwards compatibility.)

@rorywalsh Thoughts?

**Comment by tgrey1** [comment]
Oh neat!  I see the difference now...  that's a great addition!

I'll default to Rory's opinion on what could/should happen, but my two cents is that it'd be great if one function served both.  It seems like it would fit most use cases.  I wonder if it'd be possible to do something similar for a prefix too?

One caveat, I have been using newlines frequently in my popupprefix and popuppostfix to create widgets that are a little more readable... I'm not sure if that would translate to the host's gui properly?  I'll often craft something that will read like:
```
Freq:\n
440 Hz
```
by using `popupprefix("Freq:\n") popuppostfix(" Hz")`

**Comment by rorywalsh** [comment]
HI @awelex , @tgrey1, I think it would be best to have these identifiers supported for all widgets. And to consolidate the new suffix identifier with the existing ones? What say you?

**Comment by awelex** [comment]
Great, I'll get on it. How about `prefix` and `postfix` as general identifiers?

@tgrey1 That should be fine -- we can filter out `\n`, `\t` and similar escape codes for the host.

**Comment by rorywalsh** [comment]
I don't mind use `prefix()` instead of `popupprefix()`, the same goes for `postfix`. We can mark `popupprefix `as deprecated?

**Comment by tgrey1** [comment]
@awelex - Awesome!  I wasn't sure how much of a headache it would present to strip those out.

@rorywalsh - I have *OODLES* of widgets to convert to the new prefix/postfix names, but I'm perfectly OK with that.  It was a feature added at my request, and as far as I'm concerned still considered beta.  This would be a fantastic evolution of it for the betterment of Cabbage.

I'm enthusiastically on board with this!

**Comment by awelex** [comment]
Ok, I have a first attempt working here. Still need to do some more testing and refactoring before I'm ready to push.

However, I just realized that the default behavior for popup bubbles has changed between master and develop, and I'm not sure the new behavior is correct. The offending lines of code are in `initialiseSlider` (`CabbageSlider.cpp`):

NEW:
```
const String popup = CabbageWidgetData::getStringProp (wData, CabbageIdentifierIds::popuptext);
    if (CabbageWidgetData::getStringProp (wData, CabbageIdentifierIds::popuptext) == "0" || CabbageWidgetData::getStringProp (wData, CabbageIdentifierIds::popuptext)=="")
        shouldDisplayPopup = false;
    else
        shouldDisplayPopup = true;
```

OLD:
```
if (CabbageWidgetData::getStringProp (wData, CabbageIdentifierIds::popuptext) == "0")
        shouldDisplayPopup = false;
    else
        shouldDisplayPopup = true;
```

According to the manual, `popuptext(0)` is used to turn off bubbles, while `popuptext("")` denotes that the default text will be used for a bubble. The current behavior in develop doesn't adhere to that and in fact makes it impossible to specify default text behavior for bubbles. If the intent is to hide popup bubbles per default, we should just change the default value to `0` for all widgets instead of adding this new check.

If you are okay with it, I'll revert back to the old behavior.

**Comment by rorywalsh** [comment]
I think you are still a little behind the main dev branch, which looks like this:

https://github.com/rorywalsh/cabbage/blob/develop/Source/Widgets/CabbageSlider.cpp#L96-L100

But even still, I had made this change without thinking about the `popuptext(0)` option! The most recent changes had to do with [this](https://forum.cabbageaudio.com/t/no-popup-with-valuetextbox-1/1884/7) post.

**Comment by awelex** [comment]
> I think you are still a little behind the main dev branch, which looks like this:
> 
> https://github.com/rorywalsh/cabbage/blob/develop/Source/Widgets/CabbageSlider.cpp#L96-L100
> 
> But even still, I had made this change without thinking about the `popuptext(0)` option! The most recent changes had to do with [this](https://forum.cabbageaudio.com/t/no-popup-with-valuetextbox-1/1884/7) post.

Ah, I see. I'll pull in newest develop and rebase by branch then.

**Comment by rorywalsh** [comment]
Thanks. I'll merge when your are ready.

**Comment by awelex** [comment]
Hm. I'm getting a crash with newest develop whenever a combobox is used (even trying to create one in Cabbage crashes it). Note that this is vanilla develop without any of my parameter changes. Should I file a bug report?

**Comment by rorywalsh** [comment]
Yeah. I might as well start using the issues tracker in github, especially
if others are contributing 😉

**Comment by rorywalsh** [comment]
Hi @awelex. I've fixed that issue now. Can you try it out?

**Comment by awelex** [comment]
Alright, here it is. Took a little longer than expected. Here's a summary of all the changes:
- `suffix` identifier was replaced by `postfix` and a new `prefix` identifier was added
- Internally, the `prefix` and `postfix` properties hold pre- and postfix strings with escaped characters stripped. Additionally, there are new internal `prefix_escaped` and `postfix_escaped` identifiers that hold the strings with any `\n` or `\t` characters the user might have supplied. The majority of widgets use `prefix` and `postfix` while popup bubbles use `prefix_escaped` and `postfix_escaped`.
- The following widgets support `prefix` and `postfix` identifiers: sliders (including range and number sliders), encoders, and XY pads.
- For sliders, if no `prefix` or `postfix` identifier is supplied, `popupprefix` and `popuppostfix` is used as a fallback.
- Value textboxes (nslider or textboxes supplied by sliders and encoders) will not display a prefix, only a value and a postfix (if supplied). This is in keeping with the previous behavior (most likely because the user might be confused by a prefix and assume they have to type it in every time). However, the DAW will show both pre- and postfix together with the value.
- For XY pads, pre- and postfixes can be supplied for both the x and y value like this: `prefix("xPre","yPre")`

**Pull request merged**
